# Generated by Django 4.0.4 on 2022-04-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregratedMaterializedView',
            fields=[
                ('Class_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SCHOOL_TITLE', models.CharField(max_length=20)),
                ('COFFERED_WITH', models.CharField(blank=True, max_length=255, null=True)),
                ('COFFER_COURSE_ID', models.CharField(max_length=15)),
                ('SECTION', models.IntegerField()),
                ('CREDIT_HOUR', models.IntegerField()),
                ('CAPACITY', models.IntegerField()),
                ('ENROLLED', models.IntegerField()),
                ('ROOM_ID', models.CharField(max_length=12)),
                ('ROOM_CAPACITY', models.IntegerField()),
                ('COURSE_NAME', models.CharField(max_length=255)),
                ('FACULTY_NAME', models.CharField(max_length=255)),
                ('STRAT_TIME', models.CharField(max_length=50)),
                ('END_TIME', models.CharField(max_length=50)),
                ('ST_MW', models.CharField(max_length=50)),
                ('SEMESTER_NAME', models.CharField(max_length=20)),
                ('SEMESTER_YEAR', models.CharField(max_length=20)),
                ('YEAR', models.IntegerField(default=-1)),
                ('BLOCKED', models.CharField(max_length=255)),
                ('FACULTY_FULL_NAME', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Department_Code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Faculty_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Faculty_Name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('Program_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Program_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Room_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('School_ID', models.AutoField(primary_key=True, serialize=False)),
                ('School_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('Semester_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('Semester_name', models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Course_name', models.CharField(max_length=255)),
                ('Credit_hours', models.IntegerField()),
                ('Co_Offered', models.CharField(max_length=255)),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dargs.school')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Section_No', models.CharField(max_length=10)),
                ('Capacity', models.IntegerField()),
                ('Enrolled', models.IntegerField()),
                ('Start_time', models.CharField(max_length=50)),
                ('End_time', models.CharField(max_length=50)),
                ('Course_Day', models.CharField(choices=[('ST', 'ST'), ('MW', 'MW'), ('R', 'R'), ('A', 'A')], max_length=50)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dargs.course')),
                ('Department_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dargs.department')),
                ('Faculty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dargs.faculty')),
                ('Program_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dargs.program')),
                ('Room_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dargs.room')),
                ('Semester_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dargs.semester')),
            ],
        ),
    ]
