# Generated by Django 4.0.4 on 2022-04-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dargs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregratedmaterializedview',
            name='YEAR',
        ),
    ]
