# Generated by Django 4.0.4 on 2022-04-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dargs', '0002_remove_aggregratedmaterializedview_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AggregratedMaterializedView',
        ),
    ]
