export default [
  {
    tabularData: [
      {
        Enrolled: 1,
        SBE: 1,
        SELS: 0,
        SLASS: 0,
        SPPH: 0,
        Total: 1,
      },
      {
        Enrolled: 3,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 3,
        Total: 3,
      },
      {
        Enrolled: 5,
        SBE: 4,
        SELS: 0,
        SLASS: 0,
        SPPH: 2,
        Total: 6,
      },
      {
        Enrolled: 6,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 5,
        Total: 5,
      },
      {
        Enrolled: 7,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 6,
        Total: 6,
      },
      {
        Enrolled: 8,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 4,
        Total: 4,
      },
      {
        Enrolled: 10,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 7,
        Total: 7,
      },
      {
        Enrolled: 12,
        SBE: 8,
        SELS: 0,
        SLASS: 0,
        SPPH: 8,
        Total: 16,
      },
      {
        Enrolled: 13,
        SBE: 5,
        SELS: 0,
        SLASS: 0,
        SPPH: 7,
        Total: 12,
      },
      {
        Enrolled: 14,
        SBE: 3,
        SELS: 0,
        SLASS: 0,
        SPPH: 12,
        Total: 15,
      },
      {
        Enrolled: 15,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 16,
        Total: 16,
      },
      {
        Enrolled: 16,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 15,
        Total: 15,
      },
      {
        Enrolled: 17,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 11,
        Total: 11,
      },
      {
        Enrolled: 19,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 16,
        Total: 16,
      },
      {
        Enrolled: 20,
        SBE: 0,
        SELS: 0,
        SLASS: 0,
        SPPH: 25,
        Total: 25,
      },
    ],
    columns: ['Enrolled', 'SBE', 'SELS', 'SLASS', 'SPPH', 'Total'],
  },
]
